Repository avito-tech/avito-android, pull requests merged in 2020-11, with the labels that each got.

#611 MBS-9708 update gradle to 6.7
  build.gradle.kts
  gradle/wrapper/gradle-wrapper.properties
  subprojects/build.gradle.kts
  subprojects/gradle/wrapper/gradle-wrapper.properties
Labels: merge when ready

#615 Bump up infra versions
  gradle.properties
  subprojects/gradle.properties
Labels: merge when ready

#617 MBS-9865 Add pretty plain text build verdict
  subprojects/gradle/build-verdict/src/main/kotlin/com/avito/android/build_verdict/BuildVerdictPlugin.kt
  subprojects/gradle/build-verdict/src/main/kotlin/com/avito/android/build_verdict/BuildVerdictWriter.kt
  subprojects/gradle/build-verdict/src/main/kotlin/com/avito/android/build_verdict/CompositeBuildVerdictWriter.kt
  subprojects/gradle/build-verdict/src/main/kotlin/com/avito/android/build_verdict/PlainTextBuildVerdictWriter.kt
  subprojects/gradle/build-verdict/src/main/kotlin/com/avito/android/build_verdict/RawBuildVerdictWriter.kt
  subprojects/gradle/build-verdict/src/main/kotlin/com/avito/android/build_verdict/TaskErrorOutputCaptureExecutionListener.kt
  subprojects/gradle/build-verdict/src/test/kotlin/com/avito/android/build_verdict/BuildVerdictPluginTest.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/report/Report.kt
  subprojects/gradle/instrumentation-tests/src/test/kotlin/com/avito/instrumentation/InstrumentationTestsActionIntegrationTest.kt
Labels: merge when ready

#618 Recommend to use sdkman for Gradle profiler
  docs/content/docs/assemble/Benchmarks.md
  docs/content/docs/assemble/Profiling.md
Labels: build, documentation, merge when ready

#616 MBS-9825 empty suite in test apk now throws exception
  subprojects/gradle/instrumentation-tests-test-fixtures/src/main/kotlin/com/avito/instrumentation/suite/dex/FakeTestSuiteLoader.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/scheduling/InstrumentationTestsScheduler.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/suite/dex/TestSuiteLoader.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/suite/dex/TestSuiteLoaderImpl.kt
  subprojects/gradle/instrumentation-tests/src/test/kotlin/com/avito/instrumentation/suite/dex/TestSuiteLoaderIntegrationTest.kt
  subprojects/gradle/instrumentation-tests/src/test/kotlin/com/avito/instrumentation/suite/dex/TestSuiteLoaderTest.kt
Labels: merge when ready

#622 MBS-9892 bump versions
  gradle.properties
  subprojects/gradle.properties
Labels: merge when ready

#623 MBS-9509 artifactory mention in docs; remove outdated info
  docs/content/docs/assemble/Dependencies.md
  docs/content/menu/index.md
Labels: documentation, merge when ready

#620 Add testBuildVariantSupport to the ui impact analysis
  subprojects/gradle/instrumentation-test-impact-analysis/src/main/kotlin/com/avito/instrumentation/impact/InstrumentationTestImpactAnalysisExtension.kt
  subprojects/gradle/instrumentation-test-impact-analysis/src/main/kotlin/com/avito/instrumentation/impact/InstrumentationTestImpactAnalysisPlugin.kt
Labels: merge when ready

#625 version bump and cherry picks from release branch with fixes
  gradle.properties
  subprojects/gradle.properties
  subprojects/gradle/instrumentation-test-impact-analysis/src/main/kotlin/com/avito/instrumentation/impact/InstrumentationTestImpactAnalysisPlugin.kt
  subprojects/gradle/lint-report/src/main/kotlin/com/avito/android/lint/AndroidLintAccessor.kt
Labels: merge when ready

#626 Hotfix: Return deployment deletion
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/reservation/client/kubernetes/KubernetesReservationClient.kt
Labels: merge when ready

#627 Capture all tasks error logs
  subprojects/gradle/build-verdict/src/main/kotlin/com/avito/android/build_verdict/PlainTextBuildVerdictWriter.kt
  subprojects/gradle/build-verdict/src/main/kotlin/com/avito/android/build_verdict/TaskErrorOutputCaptureExecutionListener.kt
Labels: merge when ready

#628 use version with fix to deployment removal
  gradle.properties
Labels: merge when ready

#629 MBS-9086 First preparations for AGP 4.1
  subprojects/build.gradle.kts
  subprojects/gradle/impact-shared/src/main/java/com/avito/impact/configuration/AndroidTestConfiguration.kt
  subprojects/gradle/impact-shared/src/main/java/com/avito/impact/configuration/ImplementationConfiguration.kt
  subprojects/gradle/impact-shared/src/main/java/com/avito/impact/configuration/SimpleConfiguration.kt
  subprojects/gradle/impact-shared/src/main/java/com/avito/impact/configuration/TestConfiguration.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/InstrumentationTestsPlugin.kt
Labels: merge when ready

#631 MBS-7985 log pod problems (waiting and terminate states)
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/reservation/client/kubernetes/KubernetesReservationClient.kt
Labels: merge when ready

#633 Mbs 9937 lintlink
  subprojects/gradle/lint-report/src/integTest/kotlin/com/avito/android/lint/LintSlackAlertIntegrationTest.kt
  subprojects/gradle/lint-report/src/main/kotlin/com/avito/android/lint/LintReportPlugin.kt
  subprojects/gradle/lint-report/src/main/kotlin/com/avito/android/lint/LintReportTask.kt
  subprojects/gradle/lint-report/src/main/kotlin/com/avito/android/lint/slack/LintSlackReportTask.kt
  subprojects/gradle/lint-report/src/main/kotlin/com/avito/android/lint/slack/LintSlackReporter.kt
  subprojects/gradle/lint-report/src/main/kotlin/com/avito/android/lint/teamcity/TeamcityBuildLinkAccessor.kt
Labels: merge when ready

#635 MBS-9086 Fix broken screenshots tests recording
  subprojects/gradle/design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
  subprojects/gradle/design-screenshots/src/main/kotlin/com/avito/plugin/DeviceProvider.kt
  subprojects/gradle/design-screenshots/src/main/kotlin/com/avito/plugin/DeviceSearch.kt
  subprojects/gradle/design-screenshots/src/main/kotlin/com/avito/plugin/PullScreenshotsTask.kt
Labels: merge when ready

#636 MBS-9938 Bump infraVersion to 2020.30
  gradle.properties
  subprojects/gradle.properties
Labels: merge when ready

#637 MBS-9933 remove log spam
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/InstrumentationTestsTask.kt
Labels: merge when ready

#640 MBS-9086 Bump up infra version
  gradle.properties
  subprojects/gradle.properties
Labels: merge when ready

#639 MBS-8436 add detekt plugin; apply and fix UnusedPrivateMember rule
  Makefile
  subprojects/build.gradle.kts
  subprojects/common/okhttp/src/main/kotlin/com/avito/http/FallbackInterceptor.kt
  subprojects/common/okhttp/src/main/kotlin/com/avito/http/RequestBodies.kt
  subprojects/common/okhttp/src/test/kotlin/com/avito/http/FallbackInterceptorTest.kt
  subprojects/common/report-viewer/src/main/kotlin/com/avito/report/ReportsFetchApiImpl.kt
  subprojects/common/report-viewer/src/main/kotlin/com/avito/report/internal/HttpClientProvider.kt
  subprojects/detekt.yml
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/scheduling/InstrumentationTestsScheduler.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/scheduling/TestsSchedulerFactory.kt
  subprojects/gradle/lint-report/src/main/kotlin/com/avito/android/lint/LintReportPlugin.kt
  subprojects/gradle/lint-report/src/main/kotlin/com/avito/android/lint/LintReportTask.kt
  subprojects/gradle/test-summary/src/main/kotlin/com/avito/test/summary/TestSummarySender.kt
  subprojects/gradle/test-summary/src/main/kotlin/com/avito/test/summary/TestSummaryTask.kt
  subprojects/settings.gradle.kts
Labels: merge when ready

#645 MBS-10016 Bump up infra version
  gradle.properties
  subprojects/gradle.properties
Labels: merge when ready

#647 MBS-10016 Remind to check a scope before making a release
  docs/content/docs/Release.md
Labels: documentation, merge when ready

#646 Add report link to the instrumentation task verdict file
  subprojects/common/report-viewer/src/main/kotlin/com/avito/report/ReportViewerQuery.kt
  subprojects/common/report-viewer/src/test/kotlin/com/avito/report/ReportViewerQueryTest.kt
  subprojects/gradle/cd/src/test/kotlin/com/avito/ci/steps/UploadCdBuildResultIntegrationTest.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/finalizer/InstrumentationTestActionFinalizer.kt
Labels: merge when ready

#649 MBS-9988 Describe Gradle build cache
  docs/content/docs/assemble/BuildCaching.md
  docs/content/docs/projects/BuildChecks.md
  docs/content/menu/index.md
Labels: build, documentation, merge when ready

#648 Remove unused code
  subprojects/android-test/ui-testing-core/src/main/kotlin/com/avito/android/test/InteractionContext.kt
Labels: merge when ready

#651 MBS-10055 Clarify known issue for gradle properties in Mirakle
  docs/content/docs/assemble/RemoteBuild.md
  docs/content/docs/ide/Speedup.md
  docs/content/menu/index.md
Labels: build, documentation, merge when ready

#653 add DetektCheck ciStep
  subprojects/gradle/cd/src/main/kotlin/com/avito/ci/BuildStepListExtension.kt
  subprojects/gradle/cd/src/main/kotlin/com/avito/ci/steps/DetektCheck.kt
Labels: merge when ready

#655 MBS-9985 Remove unnecessary experimental plugin
  subprojects/gradle/namespaced-resources-fixer/build.gradle.kts
  subprojects/gradle/namespaced-resources-fixer/src/main/kotlin/com/avito/android/plugin/FileResourcesFixer.kt
  subprojects/gradle/namespaced-resources-fixer/src/main/kotlin/com/avito/android/plugin/FixNamespacedResourcesTask.kt
  subprojects/gradle/namespaced-resources-fixer/src/main/kotlin/com/avito/android/plugin/NamespacedResourcesFixerPlugin.kt
  subprojects/gradle/namespaced-resources-fixer/src/main/kotlin/com/avito/android/plugin/internal/ElementsExtensions.kt
  subprojects/gradle/namespaced-resources-fixer/src/main/kotlin/com/avito/android/plugin/internal/ElementsFactory.kt
  subprojects/gradle/namespaced-resources-fixer/src/main/kotlin/com/avito/android/plugin/internal/KtCompilerExtensions.kt
  subprojects/gradle/namespaced-resources-fixer/src/test/kotlin/com/avito/android/plugin/FileResourcesFixerTest.kt
  subprojects/gradle/namespaced-resources-fixer/src/test/kotlin/com/avito/android/plugin/NamespacedResourcesFixerPluginTest.kt
  subprojects/settings.gradle.kts
Labels: merge when ready

#654 add ImpactMetrics ciStep
  subprojects/gradle/cd/src/main/kotlin/com/avito/ci/BuildStepListExtension.kt
  subprojects/gradle/cd/src/main/kotlin/com/avito/ci/steps/ImpactMetrics.kt
Labels: merge when ready

#656 MBS-10055 Remove mirakle workaround for a fixed issue
  docs/content/docs/assemble/RemoteBuild.md
Labels: documentation, merge when ready

#657 bump version
  gradle.properties
  subprojects/gradle.properties
Labels: merge when ready
