Repository avito-tech/avito-android, pull requests merged in 2020-03, with the labels that each got.

#236 MBS-7515 Checking for a jira issue in the commit message
  .git_hooks/commit-msg
  .git_hooks/pre-commit
Labels: merge when ready

#235 MBS-7596 Auto merge PR when ready
  .mergify.yml
Labels: merge when ready

#237 MBS-7699 Fix typos
  docs/content/docs/test/TestMinimized.md
Labels: merge when ready

#239 MBS-7635 Fail fast when publishing to artifactory without url
  build.gradle.kts
  gradle.properties
Labels: merge when ready

#241 MBS-6553 add @JvmOverloads, groovy compatibility
  subprojects/gradle/kotlin-dsl-support/src/main/kotlin/com/avito/kotlin/dsl/ProjectExtensions.kt
Labels: merge when ready

#242 MBS-7635 Fix IDE sync
  build.gradle.kts
Labels: merge when ready

#243 MBS-5452 Revert OSX localhost issue check
  subprojects/gradle/buildchecks/src/main/kotlin/com/avito/android/plugin/build_param_check/BuildParamCheckPlugin.kt
  subprojects/gradle/buildchecks/src/main/kotlin/com/avito/android/plugin/build_param_check/GradlePropertiesCheck.kt
  subprojects/gradle/buildchecks/src/main/kotlin/com/avito/android/plugin/build_param_check/OsxLocalhostResolvingTask.kt
Labels: merge when ready

#245 MBS-1057: remove testType
  docs/content/docs/test/PerformanceTesting.md
  docs/content/docs/test/TestCaseInCode.md
  docs/content/docs/test/TestManagementSystem.md
  docs/content/menu/index.md
  subprojects/android-test/test-annotations/build.gradle.kts
  subprojects/android-test/test-annotations/src/main/kotlin/com/avito/android/test/annotations/Flaky.kt
  subprojects/android-test/test-annotations/src/main/kotlin/com/avito/android/test/annotations/Incident.kt
  subprojects/android-test/test-annotations/src/main/kotlin/com/avito/android/test/annotations/Regression.kt
  subprojects/android-test/test-annotations/src/main/kotlin/com/avito/android/test/annotations/TestType.kt
  subprojects/android-test/test-inhouse-runner/src/main/kotlin/com/avito/android/runner/InHouseInstrumentationTestRunner.kt
  subprojects/android-test/test-inhouse-runner/src/main/kotlin/com/avito/android/runner/annotation/resolver/TestMetadataAnnotationResolver.kt
  subprojects/android-test/test-report/src/main/kotlin/com/avito/android/test/report/TestPackageParser.kt
  subprojects/android-test/test-report/src/main/kotlin/com/avito/android/test/report/model/TestMetadata.kt
  subprojects/android-test/test-report/src/main/kotlin/com/avito/android/test/report/model/TestType.kt
  subprojects/android-test/test-report/src/main/kotlin/com/avito/android/test/report/transport/LocalRunTransport.kt
  subprojects/android-test/test-report/src/main/kotlin/com/avito/android/test/report/transport/PreTransportMappers.kt
  subprojects/android-test/test-report/src/test/kotlin/com/avito/android/test/report/ReportRule.kt
  subprojects/android-test/test-report/src/test/kotlin/com/avito/android/test/report/TestPackageParserTest.kt
  subprojects/common/report-viewer/src/main/kotlin/com/avito/report/ReportsAddApiImpl.kt
  subprojects/common/report-viewer/src/main/kotlin/com/avito/report/model/AndroidTest.kt
  subprojects/common/report-viewer/src/main/kotlin/com/avito/report/model/Flakiness.kt
  subprojects/common/report-viewer/src/main/kotlin/com/avito/report/model/Kind.kt
  subprojects/common/report-viewer/src/testFixtures/kotlin/com/avito/report/model/FakeTest.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/suite/TestParser.kt
Labels: merge when ready

#234 Add problem with NoClassDefFoundError in tests
  docs/content/docs/KnownIssues.md
Labels: merge when ready

#247 MBS-7343 local instrumentation run
  Makefile
  _main.sh
  gradle.properties
  subprojects/android-test/test-app/build.gradle.kts
  subprojects/android-test/test-app/gradle.properties
  subprojects/android-test/test-inhouse-runner/src/main/kotlin/com/avito/android/runner/InHouseInstrumentationTestRunner.kt
  subprojects/android-test/test-inhouse-runner/src/main/kotlin/com/avito/android/runner/TestRunEnvironment.kt
  subprojects/gradle/bitbucket/src/main/kotlin/com/avito/bitbucket/ProjectExtensions.kt
  subprojects/gradle/cd/src/test/kotlin/com/avito/ci/step/CdPluginTest.kt
  subprojects/gradle/cd/src/test/kotlin/com/avito/ci/step/PerformanceIntegrationTest.kt
  subprojects/gradle/cd/src/test/kotlin/com/avito/ci/step/UploadCdBuildResultIntegrationTest.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/InstrumentationTestsPlugin.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/InstrumentationTestsTask.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/configuration/InstrumentationPluginConfiguration.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/reservation/adb/AndroidDebugBridge.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/reservation/adb/Device.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/reservation/client/ReservationContext.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/reservation/client/kubernetes/KubernetesReservationClient.kt
  subprojects/gradle/instrumentation-tests/src/test/kotlin/com/avito/instrumentation/InstrumentationParamsBuildingTest.kt
  subprojects/gradle/instrumentation-tests/src/test/kotlin/com/avito/instrumentation/InstrumentationTestsPluginTest.kt
  subprojects/gradle/instrumentation-tests/src/testFixtures/kotlin/com/avito/instrumentation/FakeInstrumentationTestsActionParams.kt
  subprojects/gradle/instrumentation-tests/src/testFixtures/kotlin/com/avito/instrumentation/minimalInstrumentationPluginConfiguration.kt
  subprojects/gradle/kubernetes/build.gradle.kts
  subprojects/gradle/kubernetes/src/main/kotlin/com/avito/utils/gradle/KubernetesCredentials.kt
  subprojects/gradle/runner/service/src/main/kotlin/com/avito/runner/service/worker/device/adb/AdbDevicesManager.kt
  subprojects/gradle/sentry-config/src/main/kotlin/com/avito/android/sentry/EnvironmentInfoImpl.kt
  subprojects/gradle/statsd-config/src/main/kotlin/com/avito/android/stats/ProjectExtensions.kt
  subprojects/gradle/utils/src/main/kotlin/com/avito/utils/gradle/EnvArgs.kt
  subprojects/gradle/utils/src/main/kotlin/com/avito/utils/logging/CILoggingDestination.kt
Labels: merge when ready

#246 MBS-1057 filters in default config
  subprojects/gradle/instrumentation-tests-default-config/src/main/kotlin/com/avito/instrumentation/InstrumentationDefaultConfigPlugin.kt
Labels: merge when ready

#249 MBS-7669 Custom shortcode as a marker for internal resources
  docs/content/_index.md
  docs/content/docs/Contacts.md
  docs/content/docs/analytics/Analytics.md
  docs/content/docs/analytics/Statsd.md
  docs/content/docs/architecture/Dagger.md
  docs/content/docs/architecture/Modules.md
  docs/content/docs/assemble/Benchmarks.md
  docs/content/docs/assemble/BuildMetrics.md
  docs/content/docs/assemble/Minimization.md
  docs/content/docs/assemble/Mirakle.md
  docs/content/docs/cd/Artifacts.md
  docs/content/docs/cd/QApps.md
  docs/content/docs/cd/Release.md
  docs/content/docs/ci/Containers.md
  docs/content/docs/contributing/Docs.md
  docs/content/docs/contributing/FeatureToggles.md
  docs/content/docs/contributing/HowToStart.md
  docs/content/docs/test/DynamicConfig.md
  docs/content/docs/test/Manual.md
  docs/content/docs/test/ReportViewer.md
  docs/content/docs/test/TestManagementSystem.md
  docs/content/docs/test_framework/Mocking.md
  docs/themes/book/layouts/shortcodes/avito.html
Labels: merge when ready

#251 MBS-7908: fix flaky test
  subprojects/common/report-viewer/src/testFixtures/kotlin/com/avito/report/FakeReportsApi.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/report/Report.kt
  subprojects/gradle/instrumentation-tests/src/test/kotlin/com/avito/instrumentation/report/TestReporterTest.kt
Labels: merge when ready

#250 MBS-7908: ignore non-library dependencies in impact analysis
  subprojects/gradle/code-ownership/src/test/kotlin/com/avito/android/PlatformDependencyTest.kt
  subprojects/gradle/impact-shared/src/main/java/com/avito/impact/configuration/ImplementationConfiguration.kt
  subprojects/gradle/test-project/src/main/kotlin/com/avito/test/gradle/TestProjectGenerator.kt
Labels: merge when ready

#252 MBS-7688 Deprecate UITestFrameworkPerformException
  Makefile
  gradle.properties
  subprojects/android-test/test-app/src/androidTest/kotlin/com/avito/android/ui/test/InProcessClickButtonsTest.kt
  subprojects/android-test/test-inhouse-runner/src/main/kotlin/com/avito/android/runner/ReportFriendlyFailureHandler.kt
  subprojects/android-test/test-inhouse-runner/src/main/kotlin/com/avito/android/runner/UITestFrameworkPerformException.kt
Labels: merge when ready

#256 MBS-1057 bump version
  gradle.properties
Labels: merge when ready

#244 MBS-7669 Support draft pages in documentation preview
  docs/content/docs/contributing/Docs.md
  docs/local.sh
Labels: merge when ready

#248 MBS-7873 Update android lint documentation
  docs/content/docs/checks/AndroidLint.md
  docs/content/docs/ci/CIGradlePlugin.md
  subprojects/gradle/cd/src/main/kotlin/com/avito/ci/steps/UiTestCheck.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/InstrumentationTestsPlugin.kt
Labels: merge when ready

#257 MBS-7688 Skip all espresso errors in retry
  subprojects/android-test/test-app/src/androidTest/kotlin/com/avito/android/ui/test/retry/RetryScreen.kt
  subprojects/android-test/test-app/src/androidTest/kotlin/com/avito/android/ui/test/retry/RetryTest.kt
  subprojects/android-test/test-app/src/main/kotlin/com/avito/android/ui/RetryActivity.kt
  subprojects/android-test/test-inhouse-runner/src/main/kotlin/com/avito/android/runner/ReportFriendlyFailureHandler.kt
  subprojects/android-test/test-inhouse-runner/src/main/kotlin/com/avito/android/util/Wait.kt
  subprojects/android-test/ui-testing-core/src/main/kotlin/com/avito/android/test/UITestConfig.kt
  subprojects/android-test/ui-testing-core/src/main/kotlin/com/avito/android/test/Waiter.kt
  subprojects/android-test/ui-testing-core/src/main/kotlin/com/avito/android/test/matcher/RecyclerViewMatcher.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/InstrumentationTestsPlugin.kt
Labels: merge when ready

#259 change env to gradle properties
  _main.sh
  build.gradle.kts
  build.sh
  buildSrc/src/main/java/Dependencies.kt
  ci/check_onboarding.sh
  subprojects/gradle/slack/build.gradle.kts
  subprojects/gradle/slack/src/integTest/kotlin/com/avito/slack/SlackConditionalSenderIntegrationTest.kt
Labels: merge when ready

#262 MBS-7949 copy prepare-commit-msg hook from Avito project
  .git_hooks/prepare-commit-msg
Labels: merge when ready

#261 MBS-7340 Add upload build to CI plugin
  subprojects/gradle/cd/src/main/kotlin/com/avito/ci/CdPlugin.kt
  subprojects/gradle/cd/src/main/kotlin/com/avito/ci/CiCdExtension.kt
Labels: merge when ready

#260 MBS-7944 Disable report by default in runner
  subprojects/android-test/test-inhouse-runner/src/main/kotlin/com/avito/android/runner/TestRunEnvironment.kt
Labels: merge when ready

#264 Mbs 7932 synth monitoring
  subprojects/android-test/test-annotations/src/main/kotlin/com/avito/android/test/annotations/TestType.kt
  subprojects/android-test/test-inhouse-runner/src/main/kotlin/com/avito/android/runner/annotation/resolver/TestMetadataAnnotationResolver.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/suite/filter/PackagePrefixFilter.kt
  subprojects/gradle/instrumentation-tests/src/test/kotlin/com/avito/instrumentation/suite/filter/PackagePrefixFilterTest.kt
Labels: merge when ready

#265 MBS-7340 Bump up versions
  gradle.properties
Labels: merge when ready

#269 MBS-7955 bump version
  gradle.properties
Labels: merge when ready

#271 MBS-7865 fix names in clear_k8s_deployments.sh
  Makefile
  clear_k8s_deployments.sh
  subprojects/ci/k8s-deployments-cleaner/build.gradle.kts
  subprojects/ci/k8s-deployments-cleaner/src/main/kotlin/com.avito.ci/ClearK8SDeploymentsMain.kt
Labels: merge when ready

#266 Mbs 7340 qapps docs
  docs/content/docs/Infrastructure.md
  docs/content/docs/cd/QApps.md
Labels: merge when ready

#238 MBS-7854 update kotlin 1.3.61 -> 1.3.71
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  gradle.properties
  settings.gradle.kts
  subprojects/android-test/junit-utils/build.gradle.kts
  subprojects/android-test/junit-utils/src/main/java/com/avito/android/util/matcher/PropertyMatcher.kt
  subprojects/android-test/mockito-utils/build.gradle.kts
  subprojects/android-test/mockito-utils/src/main/java/com/avito/android/util/Captors.kt
  subprojects/android-test/mockito-utils/src/main/java/com/avito/android/util/MockitoUtil.kt
  subprojects/android-test/mockito-utils/src/main/java/com/avito/android/util/verification/LastCall.kt
  subprojects/android-test/mockito-utils/src/main/java/com/avito/android/util/verification/VerificationModes.kt
  subprojects/android-test/mockito-utils/src/main/java/ru/avito/util/Captors.kt
  subprojects/android-test/mockito-utils/src/main/java/ru/avito/util/MockitoMatchers.kt
  subprojects/android-test/mockito-utils/src/main/java/ru/avito/util/invocation/notMatches.kt
  subprojects/android-test/mockito-utils/src/test/java/com/avito/android/util/verification/LastCallTest.kt
  subprojects/android-test/test-inhouse-runner/build.gradle.kts
  subprojects/android-test/test-inhouse-runner/src/main/kotlin/com/avito/android/api/ApiRequest.kt
  subprojects/android-test/test-inhouse-runner/src/main/kotlin/com/avito/android/util/Mockito.kt
  subprojects/android-test/test-report/build.gradle.kts
  subprojects/android-test/test-report/src/main/kotlin/com/avito/android/test/report/transport/PreTransportMappers.kt
  subprojects/android-test/test-report/src/test/kotlin/com/avito/android/test/report/ReportRule.kt
  subprojects/android-test/test-report/src/test/kotlin/com/avito/android/test/report/ReportTest.kt
  subprojects/gradle/build-metrics/src/test/kotlin/com/avito/android/plugin/build_metrics/CollectTeamcityMetricsActionTest.kt
  subprojects/gradle/feature-toggles/src/test/kotlin/com/avito/android/plugin/SuspiciousTogglesCollectorTest.kt
  subprojects/gradle/instrumentation-tests/src/test/kotlin/com/avito/instrumentation/suite/dex/TestSuiteLoaderTest.kt
  subprojects/gradle/performance/build.gradle.kts
  subprojects/gradle/runner/client/src/test/kotlin/com/avito/runner/scheduler/EntrypointTest.kt
  subprojects/gradle/utils/build.gradle.kts
Labels: dependencies, merge when ready

#274 Mbs 7969 k8soidc
  buildSrc/src/main/kotlin/Dependencies.kt
  docs/content/docs/Infrastructure.md
  docs/content/docs/test/Runner.md
  docs/content/menu/index.md
  settings.gradle.kts
  subprojects/gradle/cd/build.gradle.kts
  subprojects/gradle/cd/src/main/kotlin/com/avito/ci/BuildStepListExtension.kt
  subprojects/gradle/cd/src/main/kotlin/com/avito/ci/steps/DocsCheckStep.kt
  subprojects/gradle/cd/src/main/kotlin/com/avito/ci/steps/DocsDeployStep.kt
  subprojects/gradle/docs/build.gradle.kts
  subprojects/gradle/docs/src/main/kotlin/com/avito/android/plugin/DeployDocsTask.kt
  subprojects/gradle/docs/src/main/kotlin/com/avito/android/plugin/DocsCheckTask.kt
  subprojects/gradle/docs/src/main/kotlin/com/avito/android/plugin/DocsExtension.kt
  subprojects/gradle/docs/src/main/kotlin/com/avito/android/plugin/DocsPlugin.kt
  subprojects/gradle/docs/src/main/kotlin/com/avito/android/plugin/DocsPluginApi.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/configuration/InstrumentationPluginConfiguration.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/executing/KubernetesTestExecutor.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/reservation/client/kubernetes/KubernetesReservationClient.kt
  subprojects/gradle/instrumentation-tests/src/testFixtures/kotlin/com/avito/instrumentation/FakeInstrumentationTestsActionParams.kt
  subprojects/gradle/kubernetes/build.gradle.kts
  subprojects/gradle/kubernetes/src/main/kotlin/com/avito/utils/gradle/Kubernetes.kt
  subprojects/gradle/kubernetes/src/main/kotlin/com/avito/utils/gradle/KubernetesCredentials.kt
Labels: dependencies, documentation, enhancement, merge when ready

#280 MBS-8048 fix test running on a clean emulator
  buildSrc/src/main/kotlin/Dependencies.kt
  subprojects/android-test/test-app/build.gradle.kts
Labels: merge when ready

#279 MBS-7651 add a posibility to filter test by report.
  Makefile
  subprojects/common/report-viewer/src/main/kotlin/com/avito/report/ReportsFetchApi.kt
  subprojects/common/report-viewer/src/main/kotlin/com/avito/report/ReportsFetchApiImpl.kt
  subprojects/common/report-viewer/src/testFixtures/kotlin/com/avito/report/FakeReportsApi.kt
  subprojects/gradle/build-environment/src/main/kotlin/com/avito/utils/gradle/EnvArgs.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/InstrumentationTestsAction.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/InstrumentationTestsPlugin.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/InstrumentationTestsTask.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/configuration/InstrumentationConfiguration.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/report/Report.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/scheduling/PerformanceTestsScheduler.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/suite/TestSuiteProvider.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/suite/filter/DownsamplingFilter.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/suite/filter/NameTestsFilter.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/suite/filter/OnlyFailedTestsFilter.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/suite/filter/TestRunFilter.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/suite/filter/TestRunsFilter.kt
  subprojects/gradle/instrumentation-tests/src/test/kotlin/com/avito/instrumentation/GetTestResultsActionTest.kt
  subprojects/gradle/instrumentation-tests/src/test/kotlin/com/avito/instrumentation/report/TestReporterTest.kt
  subprojects/gradle/instrumentation-tests/src/test/kotlin/com/avito/instrumentation/suite/TestSuiteProviderTest.kt
  subprojects/gradle/instrumentation-tests/src/test/kotlin/com/avito/instrumentation/suite/filter/HasFailedTestRunFilterTest.kt
  subprojects/gradle/instrumentation-tests/src/testFixtures/kotlin/com/avito/instrumentation/FakeInstrumentationConfigurationData.kt
  subprojects/gradle/instrumentation-tests/src/testFixtures/kotlin/com/avito/instrumentation/FakeInstrumentationTestsActionParams.kt
Labels: merge when ready

#283 MBS-7968 fail cleaner when exception occurs
  Makefile
  subprojects/ci/k8s-deployments-cleaner/src/main/kotlin/com.avito.ci/ClearK8SDeploymentsByNamespaces.kt
  subprojects/ci/k8s-deployments-cleaner/src/main/kotlin/com.avito.ci/DeleteK8SDeploymentsByNames.kt
Labels: merge when ready

#282 MBS-8042 remove unused output files
  Makefile
  subprojects/gradle/runner/shared/src/main/kotlin/com/avito/runner/CommandLineExecutor.kt
Labels: merge when ready

#281 MBS-8016 Update gradle profiler and build tools
  ci/_environment.sh
  ci/docker/android-builder/Dockerfile
  docs/content/docs/ci/Containers.md
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/suite/TestSuiteProvider.kt
Labels: merge when ready

#278 Mbs 7652 Fix in reserving new local devices
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/executing/TestExecutor.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/reservation/adb/AndroidDebugBridge.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/reservation/adb/Device.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/reservation/adb/EmulatorsLogsReporter.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/reservation/adb/LocalDevice.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/reservation/adb/RemoteDevice.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/reservation/client/ReservationClient.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/reservation/client/kubernetes/KubernetesReservationClient.kt
  subprojects/gradle/instrumentation-tests/src/main/kotlin/com/avito/instrumentation/reservation/client/local/LocalReservationClient.kt
  subprojects/gradle/runner/client/src/main/kotlin/com/avito/runner/scheduler/args/Arguments.kt
  subprojects/gradle/runner/client/src/test/kotlin/com/avito/runner/scheduler/runner/RunnerIntegrationTest.kt
  subprojects/gradle/runner/service/src/main/kotlin/com/avito/runner/service/worker/device/Device.kt
  subprojects/gradle/runner/service/src/main/kotlin/com/avito/runner/service/worker/device/Serial.kt
  subprojects/gradle/runner/service/src/main/kotlin/com/avito/runner/service/worker/device/adb/AdbDevice.kt
  subprojects/gradle/runner/service/src/main/kotlin/com/avito/runner/service/worker/device/adb/AdbDeviceParams.kt
  subprojects/gradle/runner/service/src/main/kotlin/com/avito/runner/service/worker/device/adb/AdbDeviceParser.kt
  subprojects/gradle/runner/service/src/main/kotlin/com/avito/runner/service/worker/device/model/DeviceData.kt
  subprojects/gradle/runner/service/src/main/kotlin/com/avito/runner/service/worker/device/observer/ExternalIntentionBasedDevicesObserver.kt
  subprojects/gradle/runner/service/src/test/kotlin/com/avito/runner/service/DeviceWorkerTest.kt
  subprojects/gradle/runner/service/src/test/kotlin/com/avito/runner/service/IntentionExecutionServiceTest.kt
  subprojects/gradle/runner/service/src/test/kotlin/com/avito/runner/service/worker/device/adb/AdbDeviceParserTest.kt
  subprojects/gradle/runner/shared-test/src/main/kotlin/com/avito/runner/test/Generator.kt
  subprojects/gradle/runner/shared-test/src/main/kotlin/com/avito/runner/test/mock/MockDevice.kt
Labels: merge when ready

#286 MBS-8005 fix typos and supplement documentation
  docs/content/docs/ide/Benchmarking.md
Labels: merge when ready

#288 Output clearing does not need anymore.
  subprojects/gradle/design-screenshots/src/main/kotlin/com/avito/plugin/ClearScreenshotsTask.kt
Labels: merge when ready

#287 Mbs 7806 release 2020.3.6
  build.gradle.kts
  gradle.properties
Labels: merge when ready
